export const MenuImages = {
  Chicken_Broccoli: "/assets/menuitems/img16_Chicken_Broccoli.jpg",
  Sesame_Chicken: "/assets/menuitems/img90_Sesame_Chicken_Plate.jpg",
  Chicken_Manchurian: "/assets/menuitems/img18_Chicken_Manchurian.jpg",
  Chicken_W_Garlic: "/assets/menuitems/img19_Chicken_W_Garlic.jpg",
  Hakka_Chicken: "/assets/menuitems/img20_Hakka_Chicken.jpg",
  Chicken_Bamboo_Shoot: "/assets/menuitems/img21_Chicken_Bamboo_Shoot.jpg",
  Chicken_Chilli: "/assets/menuitems/img22_Chicken_Chilli.jpg",
  Chicken_w_Mushrooms: "/assets/menuitems/img23_Chicken_w_mashrooms.jpg",
  Black_Pepper_Chicken: "/assets/menuitems/img24_Black_Pepper_Beef.jpg",
  Hunan_Chicken: "/assets/menuitems/img25_hunan_chicken.jpg",

  Chicken_Corn_Soup: "/assets/menuitems/img26_Chicken_Corn_Soup.jpg",
  Hot_Sour_Soup: "/assets/menuitems/img27_Hot_Sour_Soup.jpg",
  Egg_Drop_Soup: "/assets/menuitems/img28_Egg_Drop_Soup.jpg",
  Wonton_Soup: "/assets/menuitems/img29_Wonton_Soup.jpg",
  Tom_Yum_Soup: "/assets/menuitems/img30_Tom_Yum_Soup.jpg",

  Beef_Broccoli: "/assets/menuitems/img31_Beef_Broccoli.jpg",
  Sesame_Beef: "/assets/menuitems/img32_Sesame_Beef.jpg",
  Hakka_Beef: "/assets/menuitems/img33_Hakka_Beef.jpg",
  Beef_w_Garlic_Sauce: "/assets/menuitems/img34_Beef_w_Garlic_Sauce.jpg",
  Beef_w_Mushrooms: "/assets/menuitems/img35_Beef_w_Mushrooms.jpg",
  Beef_w_Scallion: "/assets/menuitems/img36_Beef_w_Scallion.jpg",
  Beef_Bamboo_Shoot: "/assets/menuitems/img37_Beef_Bamboo_Shoot.jpg",
  Crispy_Beef_Chilli: "/assets/menuitems/img38_Crispy_Beef_Chilli.jpg",
  Hunan_Beef: "/assets/menuitems/img39_Hunan_Beef.jpg",
  Black_Pepper_Beef: "/assets/menuitems/img24_Black_Pepper_Beef.jpg",

  Shrimp_Broccoli: "/assets/menuitems/img40_Shrimp_Broccoli.jpg",
  Sesame_Shrimp: "/assets/menuitems/img41_Sesame_Shrimp.jpg",
  Shrimp_w_Garlic_Sauce: "/assets/menuitems/img42_Shrimp_w_Garlic_Sauce.jpg",
  Hakka_Shrimp: "/assets/menuitems/img43_Hakka_Shrimp.jpg",
  Shrimp_Bamboo_Shoot: "/assets/menuitems/img44_Shrimp_Bamboo_shoot.jpg",
  Shrimp_Chilli: "/assets/menuitems/img45_Shrimp_Chilli.jpg",
  Shrimp_w_Mushrooms: "/assets/menuitems/img46_Shrimp_w_Mushrooms.jpg",
  Shrimp_Manchurian: "/assets/menuitems/img47_shrimp_manchurian.jpg",
  Fish_Chilli: "/assets/menuitems/img50_Fish_Chilli.jpg",
  Fish_Fry_Whole: "/assets/menuitems/img51_Fish_Fry_Whole.jpg",

  Chicken_Lo_Mein: "/assets/menuitems/img52_Chicken_Lo_Mein.jpg",
  Beef_Lo_Mein: "/assets/menuitems/img53_Beef_Lo_Mein.jpg",
  Shrimp_Lo_Mein: "/assets/menuitems/img54_Shrimp_Lo_Mein.jpg",
  Tofu_Lo_Mein: "/assets/menuitems/img55_Tofu_Lo_Mein.jpg",
  Vegetable_Lo_Mein: "/assets/menuitems/img56_Vegetable_Lo_Mein.jpg",
  Singapore_Noodles: "/assets/menuitems/img58_Singapore_Noodles.jpg",

  Egg_Roll: "/assets/menuitems/img13_Lollipop_Chicken.jpg",
  Chicken_Roll: "/assets/menuitems/img88_Chicken_Roll.webp",
  Chicken_Wonton: "/assets/menuitems/img113_chicken_wontons_thumb_230x300.jpg",
  Chicken_Wings: "/assets/menuitems/img128_Chicken_Wings_300x300.jpg",
  Masala_Fries: "/assets/menuitems/img137_Masala_Fries.jpg",

  Lassi: "/assets/menuitems/img62_Mango_Lassi.jpg",
  Chai_Tea: "/assets/menuitems/img63_Chai_Tea.jpg",
  Green_Tea: "/assets/menuitems/img64_Green_Tea.jpg",
  Can_Soda: "/assets/menuitems/img67_Bottled_JuiceSoda.jpg",
  Fruit_Smoothie: "/assets/menuitems/img68_Fruit_Smoothie.jpg",

  Broccoli_w_Garlic_Sauce: "/assets/menuitems/img69_Broccoli_w_Garlic_Sauce.jpg",
  Sesame_Tofu: "/assets/menuitems/img70_Sesame_Tofu.jpg",
  Vegetable_Tofu: "/assets/menuitems/img71_Vegetable_Tofu.jpg",
  Hakka_Vegetable: "/assets/menuitems/img72_Hakka_Vegetable.jpg",
  Paneer_Chilli: "/assets/menuitems/img73_Paneer_Chilli.jpg",
  Tofu_Chilli: "/assets/menuitems/img74_Tofu_Chilli.jpg",

  Chicken_Fried_Rice: "/assets/menuitems/img75_Chicken_Fried_Rice.jpg",
  Beef_Fried_Rice: "/assets/menuitems/img76_Beef_Fried_Rice.jpg",
  Shrimp_Fried_Rice: "/assets/menuitems/img77_Shrimp_Fried_Rice.jpg",
  Veg_Fried_Rice: "/assets/menuitems/img78_Veg_Fried_Rice.jpg",
  Mixed_Special_Fried_Rice: "/assets/menuitems/img79_Mixed_Special_Fried_Rice.jpg",
  White_Rice_pint: "/assets/menuitems/White-Rice-pint.jpg",
};
